services:
  regformer:
    build:
      context: docker
      dockerfile: Dockerfile
    image: tao_toolkit
    container_name: tao_toolkit
    volumes:
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./results:/workspace/results
    ipc: host # share memory with host
    ulimits:
      memlock: -1
      stack: 67108864
    tty: true
    stdin_open: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
