services:
  regformer:
    build:
      context: docker
      dockerfile: Dockerfile
    image: tao-toolkit:5.3.0-pyt
    container_name: pointpillarnet
    volumes:
      - ./data:/workspace/data
      - ./pretrained_models:/workspace/pretrained_models
    ipc: host # share memory with host
    ulimits:
      memlock: -1
      stack: 67108864
    tty: true
    stdin_open: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
